server.ssl:
  enabled: ${SSL_ENABLED:true}
  key-store-type: PKCS12
  key-store: file:${SERVER_KEYSTORE_PATH:/etc/ega/ssl/server.cert}
  key-store-password: ${SERVER_CERT_PASSWORD}

spring.rabbitmq:
  host: ${BROKER_HOST:public-mq}
  port: ${BROKER_PORT:5671}
  virtual-host: ${BROKER_VHOST:/}
  username: ${BROKER_USERNAME:admin}
  password: ${BROKER_PASSWORD:guest}
  ssl:
    enabled: true
    algorithm: TLSv1.2
    trust-store-type: PKCS12
    trust-store: file:${ROOT_CERT_PATH:/etc/ega/ssl/CA.cert}
    trust-store-password: ${ROOT_CERT_PASSWORD}
    key-store-type: PKCS12
    key-store: file:${CLIENT_CERT_PATH:/etc/ega/ssl/client.cert}
    key-store-password: ${CLIENT_CERT_PASSWORD}

elixir:
  client:
    id: ${CLIENT_ID}
    secret: ${CLIENT_SECRET}
  openid-configuration-url: ${OPENID_CONFIGURATION_URL:https://login.elixir-czech.org/oidc/.well-known/openid-configuration}

tsd:
  host: ${TSD_HOST:api.tsd.usit.no}
  access-key: ${TSD_ACCESS_KEY}
  root-ca: ${ROOT_CERT_PATH:/etc/ega/ssl/CA.cert}
  root-ca-password: ${ROOT_CERT_PASSWORD}

mq:
  exchange: ${EXCHANGE:cega}
  routing-key: ${ROUTING_KEY:files.inbox}
