server.ssl:
  key-store-type: PKCS12
  key-store: file:${SERVER_KEYSTORE_PATH:/etc/ega/ssl/server.cert}
  key-store-password: ${SERVER_CERT_PASSWORD}

spring.security.oauth2.client:
  registration:
    elixir-aai:
      client-id: ${CLIENT_ID}
      client-secret: ${CLIENT_SECRET}
      authorization-grant-type: ${AUTHORIZATION_GRANT_TYPE:authorization_code}
      redirect-uri: ${REDIRECT_URI:http://localhost:8080/oidc-protected}
      scope: ${SCOPE:openid}
  provider:
    elixir-aai:
      authorization-uri: ${AUTHORIZATION_URI:https://login.elixir-czech.org/oidc/authorize}
      token-uri: ${TOKEN_URI:https://login.elixir-czech.org/oidc/token}
      user-info-uri: ${USER_INFO_URI:https://login.elixir-czech.org/oidc/userinfo}
      user-name-attribute: ${USER_NAME_ATTRIBUTE:sub}
      jwk-set-uri: ${JWK_SET_URI:https://login.elixir-czech.org/oidc/jwk}

spring.rabbitmq:
  host: ${BROKER_HOST:public-mq}
  port: ${BROKER_PORT:5671}
  virtual-host: ${BROKER_VHOST:/}
  username: ${BROKER_USERNAME:admin}
  password: ${BROKER_PASSWORD:guest}
  ssl:
    enabled: true
    algorithm: TLSv1.2
    trust-store-type: PKCS12
    trust-store: file:${ROOT_CERT_PATH:/etc/ega/ssl/CA.cert}
    trust-store-password: ${ROOT_CERT_PASSWORD}
    key-store-type: PKCS12
    key-store: file:${CLIENT_CERT_PATH:/etc/ega/ssl/client.cert}
    key-store-password: ${CLIENT_CERT_PASSWORD}

cega:
  auth-url: ${CEGA_AUTH_URL:https://egatest.crg.eu/lega/v1/legas/users/%s?idType=username}
  username: ${CEGA_USERNAME}
  password: ${CEGA_PASSWORD}

elixir-aai.default-jku: ${JWK_SET_URI:https://login.elixir-czech.org/oidc/jwk}

tsd:
  host: ${TSD_HOST:api.tsd.usit.no}
  access-key: ${TSD_ACCESS_KEY}
  root-ca: ${ROOT_CERT_PATH:/etc/ega/ssl/CA.cert}
  root-ca-password: ${ROOT_CERT_PASSWORD}

mq:
  exchange: ${EXCHANGE:cega}
  routing-key: ${ROUTING_KEY:files.inbox}

server.port: 8081
